SET SEARCH_PATH = currentseason;

DROP TABLE IF EXISTS nationalites;
DROP TABLE IF EXISTS propose;
DROP TABLE IF EXISTS associe;
DROP TABLE IF EXISTS fait;
DROP TABLE IF EXISTS possede;
DROP TABLE IF EXISTS concerts;
DROP TABLE IF EXISTS prestataires;
DROP TABLE IF EXISTS scenes;
DROP TABLE IF EXISTS artistes;
DROP TABLE IF EXISTS partenaires;

SET SEARCH_PATH = nextseason;

DROP TABLE IF EXISTS nationalites;
DROP TABLE IF EXISTS propose;
DROP TABLE IF EXISTS associe;
DROP TABLE IF EXISTS fait;
DROP TABLE IF EXISTS possede;
DROP TABLE IF EXISTS concerts;
DROP TABLE IF EXISTS prestataires;
DROP TABLE IF EXISTS scenes;
DROP TABLE IF EXISTS artistes;
DROP TABLE IF EXISTS partenaires;

SET SEARCH_PATH = previousseasons;

DROP TABLE IF EXISTS nationalites;
DROP TABLE IF EXISTS fait;
DROP TABLE IF EXISTS possede;
DROP TABLE IF EXISTS joue;
DROP TABLE IF EXISTS "jouePrevious";
DROP TABLE IF EXISTS "faitPrevious";
DROP TABLE IF EXISTS artistes;

SET SEARCH_PATH = common;

DROP TABLE IF EXISTS actualites;
DROP TABLE IF EXISTS typeactu;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS utilisateurs;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS reseauxsociaux;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS typeprestataire;
DROP TABLE IF EXISTS typescenes;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS pays;
DROP TABLE IF EXISTS saisons;
